### ISSUE TITLE
BS environmental/habitat covariates

### ISSUE THREAD

**Issue by kjledger-NOAA** [afsc-gap-products/data-requests#105]
**Data product requested:** 
all environmental and habitat covariates compiled for EFH SDM models. for layers that vary year-to-year, please include 2021-2024 

**Output type:** 
rasters/raster stack

**Species**:
NA

**Region** :
BS (Bering Sea) - 2021 to 2024

**Research team making the request:**
Kimberly Ledger, Research Biologist, AFSC Genetics Program, kjledger-NOAA

Please let me know if you have any specific questions!

**Comment by sean-rohan-NOAA** [comment]
Transferred to [https://github.com/alaska-groundfish-efh/product-requests/issues/8](https://github.com/alaska-groundfish-efh/product-requests/issues/8)

**Comment by sean-rohan-NOAA** [comment]
Closed (https://github.com/alaska-groundfish-efh/product-requests/issues/8).

The EFH team was able to provide covariates that were used for EFH through 2019, but were unable to provide dynamic covariates for the requested time period (2021-2024) because they have not been updated for the next 5-year review.
