### ISSUE TITLE
[Arctic cod lengths from Bering Sea and Chukchi]

### ISSUE THREAD

**Issue by gdivoky** [afsc-gap-products/data-requests#63]
Fork Length or other fish length
Arctic Cod
Bering Sea  and Chukchi Sea
Cooper Island Arctic Research, G. Divoky, divoky@cooperisland.org:

**Comment by NancyRoberson** [comment]
Hi George,

Attached below are Arctic cod length frequencies from the EBS Shelf, Northern Bering Sea, and Chukchi Sea, SQL statements, and column metadata.
Please look them over the data for correctness and let me know if you have any further questions.

Thanks,
Nancy Roberson

[ArcticCodLengths_ChuckchiSea.xlsx](https://github.com/afsc-gap-products/data-requests/files/11225516/ArcticCodLengths_ChuckchiSea.xlsx)
[ArcticCodLengths_EBS.shelf.xlsx](https://github.com/afsc-gap-products/data-requests/files/11225518/ArcticCodLengths_EBS.shelf.xlsx)
[ArcticCodLengths_NBS.xlsx](https://github.com/afsc-gap-products/data-requests/files/11225519/ArcticCodLengths_NBS.xlsx)

**Comment by NancyRoberson** [comment]
Hi George,

[EBS_ArcticcodCatchesIncludingNullCatchesSince1982_AbundanceHauls.xlsx](https://github.com/afsc-gap-products/data-requests/files/11276135/EBS_ArcticcodCatchesIncludingNullCatchesSince1982_AbundanceHauls.xlsx)
Note: These data include only those records with **Abundance haul = Y**  (i.e. catch records that can be used for stock assessment because they had positive haul performance).


[ChukchiSea_ArcticcodCatchesIncludingNullCatchesSince1982_AbundanceHaulsNo.xlsx](https://github.com/afsc-gap-products/data-requests/files/11276146/ChukchiSea_ArcticcodCatchesIncludingNullCatchesSince1982_AbundanceHaulsNo.xlsx)
Note:  Since the Chukchi survey was not a classified as a stock assessment survey, all records have abundance haul values = 'N'; these data may include records with negative (poor) haul performance.

**Metadata**

- For spreadsheet column metadata, please see  [https://www.fisheries.noaa.gov/foss/f?p=215:28:16925280614594:::::](url)
![Metadata](https://user-images.githubusercontent.com/17622896/233155643-d3053590-bc0d-4735-9b93-27cf2e11d54f.JPG)

- Code definitions:  [https://www.fisheries.noaa.gov/resource/document/groundfish-survey-species-code-manual-and-data-codes-manual](url)

See tech memos for further information about each survey.
[EBS Survey Tech Memo_noaa_47705_DS1.pdf](https://github.com/afsc-gap-products/data-requests/files/11276314/EBS.Survey.Tech.Memo_noaa_47705_DS1.pdf)
[Chukchi Sea SurveyTech Memo_noaa_4777_DS1.pdf](https://github.com/afsc-gap-products/data-requests/files/11276319/Chukchi.Sea.SurveyTech.Memo_noaa_4777_DS1.pdf)
